### PR TITLE
fix compatibility with Sf5.0 Symfony\Component\HttpKernel\DataCollectorInterface

### PR DESCRIPTION
**Pull request by XuruDragon**
fix compatibility with Sf5.0 Symfony\Component\HttpKernel\DataCollectorInterface

### CODE REVIEW

**Comment by XuruDragon** [comment]
build fail but ot realted to the this PR
hint:  after tests are ok  trying to open phpunit7.4 autoload

**Comment by lunetics** [comment]
+1, we should encourage users to upgrade symfony versions on new components :)

**Comment by dunglas** [comment]
Thanks @XuruDragon

**Comment by maxhelias** [comment]
With Symfony 4.3.7 as minimum, we don't need anymore to keep compatibility for this ?
 - https://github.com/symfony/mercure-bundle/blob/master/src/DependencyInjection/Configuration.php#L32
 - https://github.com/symfony/mercure-bundle/blob/master/src/DependencyInjection/MercureExtension.php#L98

**Comment by dunglas** [comment]
Indeed, good catch. Do you want to open a PR @maxhelias? Or I can take care of it.

**Comment by maxhelias** [comment]
I can do this ;)

**Pull request merged**
